### ISSUE TITLE
[BUG] SourceMod reports Client index invalid on roundend

### ISSUE THREAD

**Issue by kubo6472** [PhlexPlexico/G5WS#24]
![image](https://user-images.githubusercontent.com/26146502/140184135-10fb8908-d9d2-413c-96c1-3c2ee21cfe85.png)
so, this started happening today. no idea what that might be.

**Comment by PhlexPlexico** [comment]
By chance are there coaches on the team?

**Comment by kubo6472** [comment]
> By chance are there coaches on the team?

Yep, one coach for one of the teams and GOTV bot. I doubt the latter is causing the trouble :D

**Comment by PhlexPlexico** [comment]
Latest pull should now fix this issue as well!

**Comment by PhlexPlexico** [comment]
Any chance you're able to test this @kubo6472? If so, I think we can mark this as closed and move on to creating a new small release!

**Comment by kubo6472** [comment]
yep, works no problem. or at least I haven't yet encountered the bug and 
since downloading it, we did like 8 matches
