### ISSUE TITLE
[Feature Request] Please update README with G5WS CVARs

### ISSUE THREAD

**Issue by JesusWithPants** [PhlexPlexico/G5WS#39]
Spending months on/off trying to figure out why match DEMOs would not upload, turns out - missing a cvar `get5_upload_demos 1`.

Please update README or Wiki with cvars and their default/possible values for other people sake :)

**Comment by PhlexPlexico** [comment]
It's kind of funny, this was mainly meant for people to really dig into the code mainly as a reason to avoid people from unnecessarily sending off requests to public panels. I suppose this is something that should be updated though since we do have ways of controlling this on the API side now.

Will look into this, thanks!

**Comment by JesusWithPants** [comment]
As a good way to do this and prevent people to simply send demo-upload requests would be if G5API/G5V webpanel auto-includes in its config-generator `get5_upload_demos 1` as a cvar if `uploadDemos` variable is set (atleast in Docker Compose)

**Comment by PhlexPlexico** [comment]
There's actually a check on the API end with that UPLOAD_DEMOS flag that will return a 413 if we are not allowing demo uploads, so something like that usually works fairly nicely, especially in a public instance. If you want, you can use a season and set it as a default CVAR, too :)

**Comment by JesusWithPants** [comment]
Yes, but would be nice to have a native solition for those who just want to spin up their own instances and not bash heads against the table trying to figure out wherein lies the fault of "no demos are uploaded" (Yes, my desk is still in one piece) 😆
