### ISSUE TITLE
The plugin is working fine expect for a few errors

### ISSUE THREAD

**Issue by BadSpider1** [PhlexPlexico/G5WS#45]
So the plugin is working fine, everything gets logged except for the rounds we played a few rounds but G5V still reported 0==0 kills map banning and such all logged fine

I also found some error in the console 

```
L 11/17/2022 - 14:39:47: [SM] Exception reported: Unable to open /home/container/csgo/get5_backup_match2_map0_round4.cfg for reading. errno: 2
L 11/17/2022 - 14:39:47: [SM] Blaming: G5WS.smx
L 11/17/2022 - 14:39:47: [SM] Call stack trace:
L 11/17/2022 - 14:39:47: [SM]   [0] SteamWorks_SetHTTPRequestRawPostBodyFromFile
L 11/17/2022 - 14:39:47: [SM]   [1] Line 669, G5WS.sp::Get5_OnRoundStart
L 11/17/2022 - 14:39:47: [SM]   [3] Call_Finish
L 11/17/2022 - 14:39:47: [SM]   [4] Line 1543, get5/scripting/get5.sp::Event_RoundStart
```

```
L 11/17/2022 - 14:39:42: [G5WS.smx] Failed to add http param key=6UZYPUEASV5H4ZOBNN7NKSL3
L 11/17/2022 - 14:39:42: [G5WS.smx] Failed to add http param PlayerDeathValues={"matchid":"2","assist":null,"no_scope":false,"event":"player_death","round_number":3,"map_number":0,"headshot":false,"round_time":17937,"thru_smoke":false,"attacker":{"side":"ct","is_bot":false,"steamid":"76561199171549369","name":"a5cvwdq2","user_id":3},"bomb":false,"attacker_blind":false,"player":{"side":"t","is_bot":false,"steamid":"76561198090495661","name":"Bonin","user_id":2},"friendly_fire":false,"weapon":{"name":"negev","id":37},"penetrated":0,"suicide":false}
```

**Comment by BadSpider1** [comment]
Just 1 we are testing

**Comment by PhlexPlexico** [comment]
Then you need to wait for the match to actually finish. If GoTV is running, it will take the time for the match to be reported if you have a recording running as well.

**Comment by BadSpider1** [comment]
So it is not supposed to change when the match is live ?
Like team 1 wins one round so on G5V its like 1==0

**Comment by PhlexPlexico** [comment]
There's two separate scores. The one that is in large text is the series score (if it's a BO1, BO3, etc it will show 0 < 1 at the end of a match, or 2>1, etc depending on how many maps are played). The per round is shown below, just above the player table, unde the `Score:`, see attached as an example from the public web panel.

![image](https://user-images.githubusercontent.com/3514085/202484583-c12d2a1c-7fd6-4460-a934-676cdba838ad.png)

**Comment by BadSpider1** [comment]
Oh, i see thanks for the help!
